### ISSUE TITLE
Thread.new Test Never Posts?

### ISSUE THREAD

**Issue by chrishough** [getsentry/raven-ruby#443]
Setup
```
if Rails.env.production? || ENV['LOG_ERRORS_TO_EXTERNAL_SERVICE']
  Raven.configure do |config|
    config.dsn = Rails.application.secrets.my_sentry_url
    config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
    config.excluded_exceptions = ['ActionController::RoutingError', 'ActiveRecord::RecordNotFound']
    config.tags = { environment: Rails.env }
    config.async = lambda { |event|
      Thread.new { Raven.send(event) }
    }
  end
end
```

When I run `bundle exec rake raven:test`  I never see the test post, however, if I remove the asyc processing it works... Thoughts?

```
require 'sentry-raven'

if Rails.env.production? || ENV['LOG_ERRORS_TO_EXTERNAL_SERVICE']
  Raven.configure do |config|
    config.dsn = Rails.application.secrets.my_sentry_url
    config.sanitize_fields = Rails.application.config.filter_parameters.map(&:to_s)
    config.excluded_exceptions = ['ActionController::RoutingError', 'ActiveRecord::RecordNotFound']
    config.tags = { environment: Rails.env }
    # config.async = lambda { |event|
    #   Thread.new { Raven.send(event) }
    # }
  end
end

```

**Comment by nateberkopec** [comment]
Yeah that's bad documentation, we need to fix that. Nothing ever #joins the thread so it never actually gets picked up.

**Comment by chrishough** [comment]
so it is safe to leave on, but it only works in production?

**Comment by nateberkopec** [comment]
No. I don't believe `Thread.new { Raven.send(event) }` works at all. We should add tests for this and make sure whatever Thread-based method we recommend actually works.

**Comment by chrishough** [comment]
bummer,  I will keep an eye out for that update

**Comment by Agent47DarkSoul** [comment]
This used to work till 0.13.3

**Comment by DaveBlooman** [comment]
Does 0.15.4 support...

```ruby
config.async = lambda { |event|
  Thread.new { Raven.send(event) }
}
```

**Comment by Agent47DarkSoul** [comment]
No, it doesn't.

**Comment by DaveBlooman** [comment]
@Agent47DarkSoul Thanks, will stick with 0.13.2 then

**Comment by nateberkopec** [comment]
Hey guys, sorry it took me so long to figure out what was going on here. So obvious in retrospect!

`Raven.send` was deprecated in `0.13.2`, because we really don't want to override the `send` method - it's one of the most important methods defined on `Object`! 

The problem with all of your code here is that you're calling `Raven.send` in a Thread, which terminates silently with a NoMethodError. [Ruby threads terminate silently upon exception unless `abort_on_exception` is set to true](http://ruby-doc.org/core-2.3.0/Thread.html#method-c-abort_on_exception-3D).

Threaded event sending works just fine in Raven with the following config:

```ruby
config.async = lambda { |event|
    Thread.new { Raven.send_event(event) }
  }
```

**Comment by chrishough** [comment]
Thank you
