### ISSUE TITLE
Rails 5 (beta 1 & beta 2) development mode broken

### ISSUE THREAD

**Issue by Elektron1c97** [getsentry/raven-ruby#456]
`undefined method [] for #<ActionDispatch::Request:0x007ff8a811b158>`

------

According to [this commit](https://github.com/getsentry/raven-ruby), the interface of the `render_exception` method changed.
Now theres no longer the env passed, instead the request is passed.
Which means to fix this, the easiest way would be, to change the `Raven::Rack.capture_type` (https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rack.rb#L24-L33) to the following:
```ruby
    def self.capture_type(exception, request, options = {})
      env = request.env
      if env['raven.requested_at']
        options[:time_spent] = Time.now - env['raven.requested_at']
      end
      Raven.capture_type(exception, options) do |evt|
        evt.interface :http do |int|
          int.from_rack(env)
        end
      end
    end
```
(more an ugly hotfix than a real fix..)

Another point:
The Rails Middleware method should have a `begin/rescue` block or maybe a `ensure` to make it easier to find the exceptions. In my case, it was very hard because rails rescued the fail made by sentry with a 500 html site, plus there was no log at all..
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails/middleware/debug_exceptions_catcher.rb#L9-L11

-----

To temporarily fix this, I added a configuration inside the Raven.configure block:

```ruby
Raven.configure do |config|
  ....
  config.catch_debugged_exceptions = false
  ....
end
```
/cc @senny

**Comment by senny** [comment]
A short follow-up to @Elektron1c97 report.

[`Raven::Rails::Middleware::DebugExceptionsCatcher`](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails/middleware/debug_exceptions_catcher.rb#L10) patches very delicate Rails code. Very minimal information will be available if the middleware to show exception details itself raises an exception. Specifically you'll get the default 500.html response produced in production. Without exception traces in the logs. The code inside the patched middleware must not raise. Since the API change mentioned by @Elektron1c97 resulted in an exception in `Raven::Rack.capture_exception(exception, env)` development mode is very much broken in Rails 5.0.0.beta1.

I suggest to either use `ensure` to always run the original `DebugExceptions` code or to present the exception thrown by `raven-sentry` to the user.

```ruby
        def render_exception_with_raven(env, exception)
          Raven::Rack.capture_exception(exception, env)
        ensure
          render_exception_without_raven(env, exception)
        end
```

or

```ruby
        def render_exception_with_raven(env, exception)
          begin
            Raven::Rack.capture_exception(exception, env)
          rescue Exception => e
            exception = e
          end
          render_exception_without_raven(env, exception)
        end
```

**Comment by nateberkopec** [comment]
Fixed in #423

**Comment by senny** [comment]
@nateberkopec thanks for the quick fix :yellow_heart:

**Comment by basiszwo** [comment]
@senny thanks for providing info to fix the issue and thanks to @nateberkopec for fixing this quickly!
