### ISSUE TITLE
Try again sending exceptions to Sentry if it fails

### ISSUE THREAD

**Issue by YtvwlD** [getsentry/raven-ruby#523]
We're running Sentry and a few webapps which report data to Sentry in a few VMs.
Everything works fine.

But when we restart the host server the VMs do not come up at the same time.
So mostly the apps are up before Sentry. When they try to log an exception during this time period, it will fail.
And Raven won't ever try again.

    E, [2016-07-11T23:35:35.907025 #300] ERROR -- : ** [Raven] Not sending event due to previous failure(s).
    E, [2016-07-11T23:35:35.907133 #300] ERROR -- : ** [Raven] Failed to submit event: <exception>
    E, [2016-07-11T23:35:35.914290 #300] ERROR -- : ** [Raven] Not sending event due to previous failure(s).
    E, [2016-07-11T23:35:35.914589 #300] ERROR -- : ** [Raven] Failed to submit event: <exception>

It would be really nice if Raven could keep reporting exceptions even if it failed one time.
It would be even better if Raven could cache those exceptions and try to report them a few times before giving up.

**Comment by nateberkopec** [comment]
[Raven performs an exponential backoff - eventually, it will try to report again, although it will not retry an exception that has failed.](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/client.rb#L118) Originally I misunderstood your question - but you want a feature where *exceptions which failed to send* are queued for eventual retry. 

Instead of us building this into the client, I suggest you use the `async` configuration feature we already offer, and then use your background job processor's "retry" feature to retry events that have failed. For example, you should be able to use Sidekiq to automatically retry failed events. Check our documentation for more on how to use `async`.
