### ISSUE TITLE
Instructions in Raven::Instance are wrong

### ISSUE THREAD

**Issue by singpolyma-shopify** [getsentry/raven-ruby#593]
The comment in https://github.com/getsentry/raven-ruby/blob/8e1a23aa844708001e91471ba28a616a335ebbe2/lib/raven/instance.rb claims you can call `Raven::Instance#capture_exception`, which does not exist.

**Comment by nateberkopec** [comment]
Good point. We usually expect people to call `Raven.capture_exception, which eventually ends up in Raven::Instance#capture_type`. We should probably just provide `capture_exception` and `capture_message` on Instance too.

**Comment by singpolyma-shopify** [comment]
`Raven.capture_exception` will only work if using a global raven instance, though, right?  So, if I'm using different instances in different places I need to call `capture_type`?

**Comment by nateberkopec** [comment]
@singpolyma-shopify Right. But that's sort of silly, because `capture_exception` is just an alias for `capture_type(Exception.new...)`. So I think we should probably fix that and add `capture_exception` to Raven::Instance.

But if you wanted to make this work today on `2.1.3`, yes, you can just `Raven::Instance.capture_type(your_exception...`
