### ISSUE TITLE
Several processors broken when using async

### ISSUE THREAD

**Issue by garjust** [getsentry/raven-ruby#622]
After this change: https://github.com/getsentry/raven-ruby/commit/a786def7b423109c964d26fae90e0b83507aac41 the async handler is passed a hash with string keys whereas `send_event` and the processors included in raven expect symbol keys in the event hash.

It is not clear that the client is expected to transform the event hash back into a hash with symbol keys before passing to `send_event`.

Just enumerating some ideas:
- `send_event` should turn all the keys into symbols
- When working with an event hash throughout the gem string keys should be used
- Revert this change and have clients JSONify the event if needed in their async proc
- Some sort of configuration option to pass the actual event object to async

**Comment by bobjflong** [comment]
This has implications for security, as the cookie and post data processors don't strip out that data, so it leaks to Sentry.

**Comment by nateberkopec** [comment]
> When working with an event hash throughout the gem string keys should be used

Yeah, this is what we're going to have to do.

**Comment by nateberkopec** [comment]
Actually, I'm going to hack around this for now. In the long term, we should just expect any hash representation of an Event to use string keys (since that's what it will look like coming out of a background job processor). But I can't change that right now because people's custom processors may expect symbols. So I'll put off the change of symbols-to-strings for 3.0 (which will be soon), but for now I'll hack around existing processors to deal with strings or symbols.
