### ISSUE TITLE
`transport_failure_callback` gives no information on failure reason

### ISSUE THREAD

**Issue by Zoetermeer** [getsentry/raven-ruby#661]
All we are given in this callback is the hash version of the event we originally intended to send, but it would be useful to also be given the exception that caused the send failure as an additional argument.  Otherwise we have no idea why the request failed in the first place.

**Comment by EtienneDepaulis** [comment]
Hello @nateberkopec I would be happy to help on this issue as it impacts us.
Is a PR on the current the best approach for you ?

**Comment by nateberkopec** [comment]
@EtienneDepaulis Yes please!

**Comment by EtienneDepaulis** [comment]
I've finally took the time to look at the code and I as I'm no ruby expert I would like to have your opinion on the best approach:

Here is the code responsible for calling the `transport_failure_callback` proc: 
```ruby
def failed_send(e, event)
  @state.failure
  if e # exception was raised
    configuration.logger.error "Unable to record event with remote Sentry server (#{e.class} - #{e.message}):\n#{e.backtrace[0..10].join("\n")}"
  else
    configuration.logger.error "Not sending event due to previous failure(s)."
  end
  configuration.logger.error("Failed to submit event: #{get_log_message(event)}")
  configuration.transport_failure_callback.call(event) if configuration.transport_failure_callback
end
```

We are interested in the properties of the error raised passed to this method by `e`. The problem is that `transport_failure_callback` expects only one param and doing something like `configuration.transport_failure_callback.call(event, e)` would be a breaking change.
But as mentioned, this feature is supposed to be introduced in v3, so those kind of changes are acceptable.

Another option would be to store the exception in the context of the event (`extra` section).

Which approche seems better for you @nateberkopec ?

**Comment by nateberkopec** [comment]
@EtienneDepaulis Open a PR with a breaking change against the `v3` branch, please.

**Comment by st0012** [comment]
close with #1003
