### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by dv** [getsentry/raven-ruby#676]
[Here](https://docs.sentry.io/clients/ruby/config/) it says as follows:

```
Raven.configure do |config|
  config.sanitize_data_for_request_methods = %w(PATCH) # Only send data for PATCH request method
  # config.processors -= [Raven::Processor::RequestMethodData] # Do this to always send request data
  config.processors -= [Raven::Processor::Cookies] # Do this to send cookies by default
end
```

Several issues:
- afaict `Raven::Processor::RequestMethodData` is only a recent addition and is not available in any released gem yet
- it's missing a `require 'raven/processor/request_method_data'` line
- it says `# Only send data for PATCH request method` but don't you mean `# Only NOT send data for PATCH request method`?
- why is `removestacktrace` in one word, but `request_method_date` with underscores? Consistency would be nice to discover these undocumented (or poorly documented) features, you'd never know you'd have to require `request_method_data` for to be able to use this processor, not `requestmethoddata`.

**Comment by nateberkopec** [comment]
> afaict Raven::Processor::RequestMethodData is only a recent addition and is not available in any released gem yet

Sorry, that's been raised before. Unfortunately the published docs always reflect master, not the latest release. We're working on a better process for this.

> it's missing a require 'raven/processor/request_method_data' line

No, it isn't - [that is required for you by Raven](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/base.rb#L9). I think you're confused because of the RemoveStacktrace example above it - that processor is not `require`d by default so you do have to `require` it yourself. It's worth noting that this is *intentionally* hard to use because removing stacktraces from Events makes Sentry half as useful, so we want to make sure You Are Completely Sure You Want To Do This.

> it says # Only send data for PATCH request method but don't you mean # Only NOT send data for PATCH request method?

Yeah that's wrong. [Fixed.](https://github.com/getsentry/raven-ruby/commit/fd5caff9b458411d2025bc72ef8afcad1d4b47c0) Made it clearer in [configuration.rb](https://github.com/getsentry/raven-ruby/commit/839d3bb738505aa21676eca0f210ea358685445a) too.

> why is removestacktrace in one word, but request_method_date with underscores? 

You know, I never even noticed our filenames were inconsistent 😆 I can fix that and deprecate the old names.

**Comment by dv** [comment]
Sweet, thanks for clearing this up! 👍 If not required anymore than the consistency is not that big of an issue, but it sure looks weird ;-)
