### ISSUE TITLE
async send may not complete when rake task terminate due to an exception

### ISSUE THREAD

**Issue by cyang16** [getsentry/raven-ruby#756]
Use async config as example
```
config.async = lambda { |event|
  Thread.new { Raven.send_event(event) }
}
```
If there is an exception raised in rake task,
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rake.rb#L9 kicks off the capture, and the capture_exception  implementation
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/instance.rb#L120 spins up an user defined async thread. But this thread is terminated before it finished, because the whole rake task terminated first.

I think raven should always use sync send_event in rake task.
Any other solutions?

**Comment by nateberkopec** [comment]
Hmmm...interesting problem. Thanks for reporting, I'll think about it.

**Comment by nateberkopec** [comment]
Couple of points:

* From what I can tell, this will not occur on JRuby.
* There's nothing we can really do about it, because we cannot access the thread you've created here to make sure we `join` it.
* Not everyone uses a thread in their async callbacks. Many use background job processors, and it would be inappropriate to disable the async callback in that case.
* You could fix this by installing an at_exit hook. You may use `concurrent-ruby`, for example, to do this for you.

In general, I don't think most people should be using a simple `Thread.new` for their async callbacks on MRI. This is documented, but I will add additional warnings.
