### ISSUE TITLE
Unable to silence <Error> excluded from capture: DSN not set

### ISSUE THREAD

**Issue by rushilagr** [getsentry/raven-ruby#793]
I am using the raven with Rails.
In dev environment, I have purposely unset the DSN.

But everytime there is an error, this message is printed - 
`<Error> excluded from capture: DSN not set`

Additionally the error gets reprinted after this as well.

How to silence the raven log?

**Comment by nateberkopec** [comment]
Raven's logger level can be changed:

```ruby
Raven.configure do |config|
  logger = ::Raven::Logger.new(STDOUT)
  logger.level = "error"
  config.logger = logger
end
```

**Comment by phoet** [comment]
would be great if one could disable raven through the configuration options.

**Comment by rushilagr** [comment]
Yeah it would. I do the same by not setting the DSN

**Comment by phoet** [comment]
looks like this is the workaround. don't like it though

**Comment by nateberkopec** [comment]
> if one could disable raven through the configuration options.

You can change the [environment settings](https://github.com/getsentry/raven-ruby/blob/master/lib/raven/configuration.rb#L24) or not set the DSN.

**Comment by alexanderadam** [comment]
I'm sorry for reviving this ticket:

@nateberkopec so far I have

1. setting the environments
2. not setting `config.dsn`
3. not setting `SENTRY_DSN`

and even

4.  not having a `Raven.configure`-block at all

But in all cases I still see `excluded from capture: DSN not set` in the `development` environment.

Why's that? Well, here's why:

It's still buggy: I'm just setting the DSN in the relevant in `production` and `staging` which totally makes sense because I'm not going to catch sentry errors here.
But due to the [order in `Configuration#capture_allowed?`](https://github.com/getsentry/raven-ruby/blob/263a33b94d9a689d0fc5ba5c16bc92be9538e9fb/lib/raven/configuration.rb#L308-L309) this leads to a situation that the relevant part (`Configuration#capture_in_current_environment?`) won't even be reached because, although totally irrelevant in this case, `Configuration#valid?` will be called and [adds `DSN not set` to `@errors`](https://github.com/getsentry/raven-ruby/blob/263a33b94d9a689d0fc5ba5c16bc92be9538e9fb/lib/raven/configuration.rb#L433) and returns `false`.
So this irrelevant "error" [will appear to the log](https://github.com/getsentry/raven-ruby/blob/263a33b94d9a689d0fc5ba5c16bc92be9538e9fb/lib/raven/instance.rb#L107) and `Configuration#capture_in_current_environment?` won't even be touched although it's the only relevant thing here. And even **if** we would switch and call `Configuration#valid?` and `Configuration#capture_in_current_environment?` we would see `excluded from capture: Not configured to send/capture in environment 'development'` in the logs. Which we know, because we set it explicitly anyway, so it is **not** an error although it is added to `@errors`.

Also the README is therefore misleading. The headline [`Raven only runs when SENTRY_DSN is set` is not quite true](https://github.com/alexanderadam/raven-ruby#raven-only-runs-when-sentry_dsn-is-set). Raven just **sends** stuff when the dsn is set, but it will still pollute the logs.

Otherwise I just might have missed a detail and I would be happy to know which one. Because I guess it must somehow be easy to just silence Raven somehow, when it isn't wanted.

PS: isn't this a duplicate of #539

**Comment by pond** [comment]
Following this up as agree with @alexanderadam - this definitely not a duplicate of #539 and IMHO needs to be re-opened as definitely a bug.

The documentation says "Don't set the DSN and Raven is disabled" but then Raven sits there going "waaah you didn't set the DSN!" into my logs :-)

I want to be able to _turn Raven off_ and be sure it's turned off in e.g. dev or test modes. I don't want to see warning-like stuff catching my attention in logs as it's distracting me from other potentially significant actual warning-like stuff therein.

Would love to see this reopened & fixed if at all possible. Thanks!

**Comment by st0012** [comment]
Hi thanks for all the discussions, https://github.com/getsentry/raven-ruby/pull/1000 should fix the issue 😄
