### ISSUE TITLE
Context should accept procs as values

### ISSUE THREAD

**Issue by fabn** [getsentry/raven-ruby#963]
I used other error tracking libraries and what I'm missing in sentry is the ability to provide context using a proc.

If I provide context in a before action as in the provided example 

```ruby
before_action -> do
  Raven.user_context = user_context
  Raven.tags_context = context_tags
end
```

when filter is run some values may not yet be available. If we're able to provide a proc (evaluated with current controller) we can add more useful data to context and get it when available.

Also I see that you're using thread locals (correctly) but you don't suggest to clear context after usage, this can leak context to other requests served by same thread. I'm using like this to avoid this issue.

```ruby
  around_action :set_diagnostic_context

  # Used to record values in sentry
  def set_diagnostic_context(&action)
    Raven.user_context = user_context
    Raven.tags_context = context_tags
    action.call
  ensure
    Raven::Context.clear!
  end
```

is that correct?

**Comment by st0012** [comment]
If you want to insert some information that's only available after the `before_action` callback, you can use `Raven.tags.merge!(key: val)` to add it to the context.

It could be a bit less convenient than passing a proc value. But since it's achievable, I don't want to support proc value at the moment as the benefit won't worth the added complexity.

> Also I see that you're using thread locals (correctly) but you don't suggest to clear context after usage, this can leak context to other requests served by same thread. I'm using like this to avoid this issue.

We do clean up the context in rack middleware, so you don't need to do it manually

https://github.com/getsentry/raven-ruby/blob/cd628e00ab7231e3d18d771ffd232db9c7b387c0/lib/raven/integrations/rack.rb#L60-L67
